image: archlinux
packages:
  - rustup
sources:
  - https://git.sr.ht/~swaits/vivaldi-nc
tasks:
  - setup: |
      rustup toolchain install nightly stable
      cd vivaldi-nc/
      rustup run stable cargo fetch
  - format: |
      rustup default stable
      cd vivaldi-nc/
      cargo fmt --verbose --check
  - lint: |
      rustup default stable
      cd vivaldi-nc/
      cargo clippy --verbose
  - stable: |
      rustup default stable
      cd vivaldi-nc/
      cargo build --verbose
      cargo test --verbose --no-default-features --features f32
      cargo test --verbose --no-default-features --features f64
  - nightly: |
      rustup default nightly
      cd vivaldi-nc/
      cargo clippy --verbose ||:
      cargo build --verbose  ||:
      cargo test --verbose --no-default-features --features f32 ||:
      cargo test --verbose --no-default-features --features f64 ||:
  - bench: |
      rustup default stable
      cd vivaldi-nc/
      cargo bench --verbose --no-default-features --features f32
      cargo bench --verbose --no-default-features --features f64
  - examples: |
      rustup default stable
      cd vivaldi-nc/
      cargo run --verbose --no-default-features --features f32 --example planetlab
      cargo run --verbose --no-default-features --features f64 --example planetlab
      cargo run --verbose --no-default-features --features f32 --example planetlab --release
      cargo run --verbose --no-default-features --features f64 --example planetlab --release
  - docs: |
      cd vivaldi-nc/
      rustup run stable cargo doc --no-deps
      rustup run nightly cargo doc --no-deps ||:
