image: archlinux
packages:
  - rustup
sources:
  - https://git.sr.ht/~swaits/vivaldi-nc
tasks:
  - setup: |
      rustup toolchain install nightly stable
      cd vivaldi-nc/
      rustup run stable cargo fetch
  - stable: |
      rustup default stable
      cd vivaldi-nc/
      cargo fmt --verbose --check
      cargo clippy --verbose
      cargo build --verbose
      cargo test --verbose
  - nightly: |
      rustup default nightly
      cd vivaldi-nc/
      cargo clippy --verbose ||:
      cargo build --verbose  ||:
      cargo test --verbose   ||:
  - docs: |
      cd vivaldi-nc/
      rustup run stable cargo doc --no-deps
      rustup run nightly cargo doc --no-deps ||:
